version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "execise-hel-sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-v340zkhxe4cx"
s3_prefix = "execise-hel-sam-app"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "execise-hel-sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-v340zkhxe4cx"
s3_prefix = "execise-hel-sam-app"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
