AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  execise-hel-sam-app

  Sample SAM Template for execise-hel-sam-app

Resources:
  PrepareFoodsStepFunction:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      DefinitionUri: step_functions/prepare_foods.json
      DefinitionSubstitutions:
        DeliveryFunctionArn: !GetAtt DeliveryFunctionArn.Arn
        SendMailFunctionArn: !GetAtt SendMailFunction.Arn
      Events:
        HourlyTradingSchedule:
          Type: Schedule # More info about Schedule Event Source: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-statemachine-schedule.html
          Properties:
            Description: Schedule to run the stock trading state machine every hour
            Enabled: False # This schedule is disabled by default to avoid incurring charges.
            Schedule: "rate(1 hour)"
      Policies: # Find out more about SAM policy templates: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - LambdaInvokePolicy:
            FunctionName: !Ref DeliveryFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref SendMailFunction

  DeliveryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/delivery/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x

  SendMailToMemberFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/send-mail-to-member/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PrepareFoodsStepFunctionArn:
    Description: "Stock Trading state machine ARN"
    Value: !Ref PrepareFoodsStepFunction
  PrepareFoodsStepFunctionRole:
    Description: "IAM Role created for Stock Trading state machine based on the specified SAM Policy Templates"
    Value: !GetAtt PrepareFoodsStepFunctionRole.Arn
